# Generated by Django 4.0 on 2021-12-28 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('testName', models.CharField(max_length=50)),
                ('testDescription', models.CharField(max_length=100)),
                ('testPrice', models.FloatField()),
                ('testUniqueId', models.CharField(blank=True, max_length=50)),
                ('sampleColllectionCharges', models.CharField(choices=[(True, 'Yes'), (False, 'No')], max_length=1)),
                ('dicount', models.FloatField()),
                ('finalCost', models.FloatField(max_length=50)),
            ],
        ),
    ]
