# Generated by Django 4.0 on 2021-12-28 08:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('package', '0002_rename_finalcost_test_final_cost_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='test',
            old_name='dicount',
            new_name='disount',
        ),
    ]
