# Generated by Django 4.0 on 2021-12-28 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('package', '0003_rename_dicount_test_disount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='disount',
            field=models.CharField(help_text='You Can Ammount or Percent of Ammount Eg: 100 or 10%', max_length=10),
        ),
    ]
