# Generated by Django 4.0 on 2021-12-28 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('package', '0005_alter_test_final_cost'),
    ]

    operations = [
        migrations.RenameField(
            model_name='test',
            old_name='disount',
            new_name='discount',
        ),
        migrations.AlterField(
            model_name='test',
            name='sample_colllection_charges',
            field=models.CharField(choices=[('1', 'Yes'), ('0', 'No')], max_length=1),
        ),
    ]
