# Generated by Django 4.0 on 2021-12-28 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('package', '0006_rename_disount_test_discount_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Profile_Id', models.CharField(blank=True, max_length=50)),
                ('Profile_Name', models.CharField(max_length=50)),
                ('profile_description', models.TextField()),
                ('Publish', models.CharField(choices=[('1', 'Yes'), ('0', 'No')], max_length=1)),
                ('Select_Test_id', models.ManyToManyField(to='package.Test')),
            ],
        ),
    ]
