# Generated by Django 4.0 on 2021-12-28 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('package', '0007_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='Select_Test_id',
            field=models.ManyToManyField(to='package.test'),
        ),
    ]
