# Generated by Django 4.0 on 2021-12-28 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('package', '0008_alter_profile_select_test_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='PackageAvailablefor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='package',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Package_id', models.CharField(blank=True, max_length=50)),
                ('Package_name', models.CharField(max_length=50)),
                ('Package_descrption', models.TextField()),
                ('Package_price', models.FloatField()),
                ('discount', models.CharField(help_text='You Can Ammount or Percent of Ammount Eg: 100 or 10%', max_length=10)),
                ('Package_for', models.ManyToManyField(to='package.PackageAvailablefor')),
                ('Porfile_collection', models.ManyToManyField(to='package.profile')),
            ],
        ),
    ]
