# Generated by Django 4.0 on 2021-12-29 07:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('UserData', '0001_initial'),
        ('package', '0009_packageavailablefor_package'),
    ]

    operations = [
        migrations.CreateModel(
            name='coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Coupon_id', models.CharField(max_length=50)),
                ('coupan_name', models.CharField(max_length=50)),
                ('Generate_coupon', models.CharField(blank=True, help_text='Add coupon or leave blank to genrate automatically..', max_length=50)),
                ('Coupon_expire_date', models.DateField()),
                ('Coupon_partical_allowes', models.CharField(choices=[('1', 'Yes'), ('0', 'No')], max_length=1)),
                ('Coupon_created', models.DateField(auto_now=True)),
                ('discount', models.CharField(help_text='You Can Ammount or Percent of Ammount Eg: 100 or 10%', max_length=10)),
                ('minimum_order_value', models.FloatField()),
                ('active', models.CharField(choices=[('1', 'Yes'), ('0', 'No')], max_length=1)),
                ('Copon_issed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='UserData.user')),
            ],
        ),
    ]
