# Generated by Django 4.0 on 2021-12-29 07:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('package', '0010_coupon'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coupon',
            old_name='Copon_issed_by',
            new_name='Coupon_issed_by',
        ),
    ]
