# Generated by Django 4.0 on 2021-12-29 08:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('UserData', '0001_initial'),
        ('package', '0011_rename_copon_issed_by_coupon_coupon_issed_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='Coupon_issed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='UserData.user'),
        ),
    ]
