# Generated by Django 4.0 on 2022-01-25 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('package', '0016_faqs'),
    ]

    operations = [
        migrations.CreateModel(
            name='tempbooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bookingid', models.TextField()),
                ('tempbookingid', models.CharField(max_length=20)),
                ('ammount', models.CharField(max_length=20)),
            ],
        ),
    ]
