# Generated by Django 4.0 on 2022-01-26 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('package', '0018_category_subcategory_package_package_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='popular_package',
            field=models.BooleanField(default=False),
        ),
    ]
