# Generated by Django 4.0 on 2022-01-26 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('package', '0019_package_popular_package'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subcategory',
            name='describe',
        ),
    ]
