# Generated by Django 4.0 on 2022-01-26 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('package', '0022_category_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='subcategory',
            unique_together={('category', 'name')},
        ),
    ]
