# Generated by Django 4.0 on 2022-01-27 09:35

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('package', '0024_alter_package_package_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subcategory',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True),
        ),
        migrations.AddField(
            model_name='subcategory',
            name='shortdes',
            field=models.TextField(blank=True),
        ),
    ]
