# Generated by Django 4.0 on 2022-01-27 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('package', '0027_alter_package_package_descrption'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='Publish',
            field=models.CharField(choices=[('1', 'Yes'), ('0', 'No')], default=1, max_length=1),
            preserve_default=False,
        ),
    ]
