# Generated by Django 4.0 on 2022-01-27 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('package', '0028_test_publish'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='Publish',
            field=models.CharField(choices=[('1', 'Yes'), ('0', 'No')], default='1', max_length=1),
            preserve_default=False,
        ),
    ]
