# Generated by Django 4.0 on 2022-01-27 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('package', '0030_test_test_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='slug',
            field=models.SlugField(blank=True),
        ),
    ]
