# Generated by Django 4.0 on 2022-01-28 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('package', '0032_alter_test_test_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='package_category',
            field=models.ManyToManyField(blank=True, related_name='package', to='package.Subcategory'),
        ),
        migrations.AlterField(
            model_name='test',
            name='test_category',
            field=models.ManyToManyField(blank=True, related_name='test', to='package.Subcategory'),
        ),
    ]
