# Generated by Django 4.0 on 2022-02-09 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('package', '0034_subcategory_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='Generate_coupon',
            field=models.CharField(blank=True, help_text='Add coupon or leave blank to genrate automatically..', max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='Select_Test_id',
            field=models.ManyToManyField(related_name='profile', to='package.test'),
        ),
    ]
