# Generated by Django 4.0 on 2022-02-09 13:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('UserData', '0027_prescriptions_image1_prescriptions_image2_and_more'),
        ('package', '0035_alter_coupon_generate_coupon_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tempbooking',
            name='coupon',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='tempbooking',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tempbooking', to='UserData.user'),
        ),
    ]
