# Generated by Django 4.0 on 2022-02-09 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('package', '0036_tempbooking_coupon_tempbooking_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='tempbooking',
            name='status',
            field=models.CharField(choices=[('success', 'success'), ('pending', 'pending')], default='pending', max_length=10),
        ),
    ]
