# Generated by Django 4.0 on 2022-02-10 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('package', '0039_remove_tempbooking_bookingid_tempbooking_bookingid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tempbooking',
            name='bookingid',
        ),
        migrations.AddField(
            model_name='tempbooking',
            name='bookingid',
            field=models.TextField(default='120'),
            preserve_default=False,
        ),
    ]
