# Generated by Django 4.0 on 2022-02-26 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserData', '0029_alter_booking_status'),
        ('package', '0041_remove_tempbooking_bookingid_tempbooking_bookingid'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='quantity',
            field=models.IntegerField(default=100),
        ),
        migrations.AddField(
            model_name='coupon',
            name='remaining',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='coupon',
            name='used',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='package',
            name='Porfile_collection',
            field=models.ManyToManyField(related_name='package', to='package.profile'),
        ),
        migrations.AlterField(
            model_name='tempbooking',
            name='bookingid',
            field=models.ManyToManyField(related_name='Transtaction', to='UserData.Booking'),
        ),
    ]
