# Generated by Django 3.2 on 2021-12-01 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paymentintigration', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paytmconfig',
            name='PostUrl',
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
