# Generated by Django 3.2.9 on 2021-12-10 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paymentintigration', '0003_rozpayconfig'),
    ]

    operations = [
        migrations.CreateModel(
            name='paypalConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='add mode for example "( testing config )" ', max_length=100)),
                ('RECEIVER_EMAIL', models.CharField(max_length=100)),
                ('activate', models.BooleanField(default=False, help_text=':- check to activate')),
            ],
        ),
    ]
