# Generated by Django 3.2.9 on 2021-12-10 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paymentintigration', '0004_paypalconfig'),
    ]

    operations = [
        migrations.AddField(
            model_name='paypalconfig',
            name='test',
            field=models.BooleanField(default=False, help_text=':- check If you want to test payment method'),
        ),
    ]
