# Generated by Django 4.0 on 2022-02-10 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paymentintigration', '0005_paypalconfig_test'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaytmTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CURRENCY', models.CharField(blank=True, max_length=4)),
                ('GATEWAYNAME', models.CharField(blank=True, max_length=15)),
                ('RESPMSG', models.CharField(blank=True, max_length=50)),
                ('BANKNAME', models.CharField(blank=True, max_length=50)),
                ('PAYMENTMODE', models.CharField(blank=True, max_length=50)),
                ('MID', models.CharField(blank=True, max_length=50)),
                ('RESPCODE', models.CharField(blank=True, max_length=50)),
                ('TXNID', models.CharField(blank=True, max_length=50)),
                ('TXNAMOUNT', models.CharField(blank=True, max_length=50)),
                ('ORDERID', models.CharField(blank=True, max_length=50)),
                ('STATUS', models.CharField(blank=True, max_length=50)),
                ('BANKTXNID', models.CharField(blank=True, max_length=50)),
                ('TXNDATE', models.CharField(blank=True, max_length=50)),
                ('CHECKSUMHASH', models.CharField(blank=True, max_length=50)),
            ],
        ),
    ]
