# Generated by Django 4.0 on 2022-02-10 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paymentintigration', '0006_paytmtransaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paytmtransaction',
            name='TXNDATE',
            field=models.DateTimeField(),
        ),
    ]
