# Generated by Django 3.2.8 on 2021-11-29 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superuser', '0002_alter_about_content'),
    ]

    operations = [
        migrations.CreateModel(
            name='aboutContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(upload_to='logo')),
                ('phone', models.CharField(help_text='enter the 10 digit phone with country code example +91987654321', max_length=13)),
                ('email', models.EmailField(max_length=254)),
                ('country', models.CharField(default='india', max_length=20)),
                ('state', models.CharField(default='Madhya Pradesh', max_length=50)),
                ('city', models.CharField(default='Indore', max_length=50)),
                ('BuildingNo', models.CharField(blank=True, help_text='Optional', max_length=100)),
                ('address', models.CharField(max_length=200)),
            ],
        ),
        migrations.DeleteModel(
            name='about',
        ),
    ]
