# Generated by Django 3.2.8 on 2021-11-29 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superuser', '0003_auto_20211129_1736'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutcontact',
            name='workingHours',
            field=models.CharField(default='Mon to Fri: 9am to 8pm', max_length=50),
        ),
    ]
