# Generated by Django 3.2.8 on 2021-11-29 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superuser', '0004_aboutcontact_workinghours'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutcontact',
            name='facebook',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='aboutcontact',
            name='fliker',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='aboutcontact',
            name='instagram',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='aboutcontact',
            name='linkedin',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='aboutcontact',
            name='twiter',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
