# Generated by Django 4.0 on 2021-12-28 05:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('superuser', '0005_auto_20211129_1757'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aboutcontact',
            name='BuildingNo',
        ),
        migrations.RemoveField(
            model_name='aboutcontact',
            name='address',
        ),
        migrations.RemoveField(
            model_name='aboutcontact',
            name='city',
        ),
        migrations.RemoveField(
            model_name='aboutcontact',
            name='country',
        ),
        migrations.RemoveField(
            model_name='aboutcontact',
            name='email',
        ),
        migrations.RemoveField(
            model_name='aboutcontact',
            name='facebook',
        ),
        migrations.RemoveField(
            model_name='aboutcontact',
            name='fliker',
        ),
        migrations.RemoveField(
            model_name='aboutcontact',
            name='instagram',
        ),
        migrations.RemoveField(
            model_name='aboutcontact',
            name='linkedin',
        ),
        migrations.RemoveField(
            model_name='aboutcontact',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='aboutcontact',
            name='state',
        ),
        migrations.RemoveField(
            model_name='aboutcontact',
            name='twiter',
        ),
        migrations.RemoveField(
            model_name='aboutcontact',
            name='workingHours',
        ),
    ]
