# Generated by Django 4.0 on 2021-12-28 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superuser', '0006_remove_aboutcontact_buildingno_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutcontact',
            name='AdminTitle',
            field=models.CharField(default='Sequal Administration', max_length=30),
            preserve_default=False,
        ),
    ]
