# Generated by Django 4.0 on 2021-12-28 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superuser', '0007_aboutcontact_admintitle'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutcontact',
            name='favicon',
            field=models.ImageField(default='', upload_to='logo'),
            preserve_default=False,
        ),
    ]
