# Generated by Django 4.0 on 2022-01-04 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superuser', '0008_aboutcontact_favicon'),
    ]

    operations = [
        migrations.CreateModel(
            name='emailSetup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host', models.CharField(max_length=100)),
                ('port', models.IntegerField()),
                ('tsl', models.BooleanField()),
                ('ssl', models.BooleanField()),
                ('email', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('activate', models.BooleanField(help_text='other mail is automatically disabled')),
            ],
        ),
    ]
