# Generated by Django 4.0 on 2022-01-27 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='contactMails',
        ),
        migrations.AddField(
            model_name='contactinfo',
            name='email',
            field=models.EmailField(default='info@sequeldiagnosticservices.com', max_length=254),
        ),
    ]
