# Generated by Django 4.0 on 2022-01-27 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_delete_contactmails_contactinfo_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer_contact',
            old_name='company',
            new_name='subject',
        ),
    ]
