# Generated by Django 4.0 on 2022-01-27 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_rename_company_customer_contact_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer_contact',
            name='message',
            field=models.TextField(),
        ),
    ]
