# Generated by Django 4.0 on 2022-02-09 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_homeslider'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homeslider',
            name='url',
            field=models.CharField(help_text='Copy and Paste The Url of Page your want to redirect', max_length=100),
        ),
    ]
