# Generated by Django 4.0 on 2022-02-09 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_alter_homeslider_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='homeslider',
            name='name',
            field=models.CharField(default='RTPCR TEST', max_length=50),
            preserve_default=False,
        ),
    ]
