# Generated by Django 4.0 on 2021-12-29 09:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('package', '0013_alter_coupon_coupon_id'),
        ('UserData', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('package', 'package'), ('test', 'test')], max_length=10)),
                ('package', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='package.package')),
                ('test', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='package.test')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UserData.user')),
            ],
        ),
    ]
