# Generated by Django 4.0 on 2021-12-29 12:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('UserData', '0003_alter_booking_user_report'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='Booking_id',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='report',
            name='booking',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='report', to='UserData.booking'),
        ),
    ]
