# Generated by Django 4.0 on 2022-01-04 05:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserData', '0004_booking_booking_id_alter_report_booking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='report',
            field=models.FileField(upload_to='reports', validators=[django.core.validators.FileExtensionValidator(['pdf', 'tif', 'jpg', 'jpeg', 'gif', 'png', 'docx'])]),
        ),
    ]
