# Generated by Django 4.0 on 2022-01-11 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserData', '0006_report_content_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='bio',
        ),
        migrations.RemoveField(
            model_name='user',
            name='birth_date',
        ),
        migrations.RemoveField(
            model_name='user',
            name='location',
        ),
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.CharField(default='', max_length=13),
            preserve_default=False,
        ),
    ]
