# Generated by Django 4.0 on 2022-01-11 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserData', '0008_alter_user_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='TempUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=13)),
                ('otp', models.CharField(max_length=8)),
                ('expire', models.DateTimeField()),
            ],
        ),
    ]
