# Generated by Django 4.0 on 2022-01-12 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserData', '0010_user_dob_user_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='dob',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(blank=True, max_length=5),
        ),
    ]
