# Generated by Django 4.0 on 2022-01-12 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserData', '0011_alter_user_dob_alter_user_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='dob',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
