# Generated by Django 4.0 on 2022-01-18 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserData', '0012_alter_user_dob_alter_user_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile',
            field=models.ImageField(default='profile/default.jpg', upload_to='profiles'),
        ),
    ]
