# Generated by Django 4.0 on 2022-01-18 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserData', '0014_family'),
    ]

    operations = [
        migrations.AddField(
            model_name='family',
            name='email',
            field=models.EmailField(default='test@gmail.com', max_length=254),
            preserve_default=False,
        ),
    ]
