# Generated by Django 4.0 on 2022-01-25 09:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('package', '0016_faqs'),
        ('UserData', '0015_family_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='family',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Family', to='UserData.user'),
        ),
        migrations.CreateModel(
            name='cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('package', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='package.package')),
                ('test', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='package.test')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UserData.user')),
            ],
        ),
    ]
