# Generated by Django 4.0 on 2022-01-25 11:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('UserData', '0016_alter_family_user_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='collectiontime',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
