# Generated by Django 4.0 on 2022-01-25 12:00

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('UserData', '0017_booking_collectiontime'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='bookingfor',
            field=models.CharField(choices=[('self', 'self'), ('child', 'child'), ('perent', 'perent'), ('grand parent', 'grand parent'), ('friend', 'friend'), ('relative', 'relative'), ('other', 'other'), ('collieague', 'collieague'), ('other', 'other')], max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='booking',
            name='member',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='UserData.family'),
        ),
    ]
