# Generated by Django 4.0 on 2022-01-25 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserData', '0018_booking_bookingfor_booking_member'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('success', 'success'), ('pending', 'pending'), ('failed', 'failed')], default='pending', max_length=20),
        ),
    ]
