# Generated by Django 4.0 on 2022-01-26 13:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('package', '0024_alter_package_package_category_and_more'),
        ('UserData', '0019_booking_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='package',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Booking', to='package.package'),
        ),
    ]
