# Generated by Django 4.0 on 2022-01-27 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserData', '0020_alter_booking_package'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequestedCallBack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('booking', 'booking'), ('support', 'support')], max_length=100)),
                ('mobile', models.CharField(max_length=13)),
                ('name', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=50)),
            ],
        ),
    ]
