# Generated by Django 4.0 on 2022-01-28 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserData', '0021_requestedcallback'),
    ]

    operations = [
        migrations.CreateModel(
            name='userAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=100)),
                ('houseno', models.CharField(max_length=200)),
                ('pin', models.CharField(max_length=8)),
                ('state', models.CharField(max_length=100)),
                ('default', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='cart',
            name='type',
            field=models.CharField(default='', max_length=10),
            preserve_default=False,
        ),
    ]
