# Generated by Django 4.0 on 2022-01-29 13:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('UserData', '0023_useraddress_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='UserData.useraddress'),
        ),
    ]
