# Generated by Django 4.0 on 2022-02-05 10:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('UserData', '0024_booking_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prescriptions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UserData.user')),
            ],
        ),
        migrations.CreateModel(
            name='prescriptionImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='Prescriptions')),
                ('pres', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='UserData.prescriptions')),
            ],
        ),
    ]
