# Generated by Django 4.0 on 2022-02-05 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserData', '0025_prescriptions_prescriptionimage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='prescriptionimage',
            old_name='pres',
            new_name='property',
        ),
        migrations.AlterField(
            model_name='prescriptionimage',
            name='image',
            field=models.ImageField(upload_to=''),
        ),
    ]
