# Generated by Django 4.0 on 2022-02-05 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserData', '0026_rename_pres_prescriptionimage_property_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescriptions',
            name='image1',
            field=models.ImageField(blank=True, upload_to='prescription'),
        ),
        migrations.AddField(
            model_name='prescriptions',
            name='image2',
            field=models.ImageField(blank=True, upload_to='prescription'),
        ),
        migrations.AddField(
            model_name='prescriptions',
            name='image3',
            field=models.ImageField(blank=True, upload_to='prescription'),
        ),
        migrations.DeleteModel(
            name='prescriptionImage',
        ),
    ]
