# Generated by Django 4.0 on 2022-02-10 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserData', '0027_prescriptions_image1_prescriptions_image2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('cod', 'Cash On Delhivery'), ('success', 'success'), ('pending', 'pending'), ('failed', 'failed')], default='pending', max_length=20),
        ),
    ]
