# Generated by Django 4.0 on 2022-02-26 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserData', '0028_alter_booking_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('cod', 'Cash on sample collection'), ('success', 'success'), ('pending', 'pending'), ('failed', 'failed')], default='pending', max_length=20),
        ),
    ]
